(() => {
 'use strict';
 const $=s=>document.querySelector(s),account=window.WackyAccount,dialog=$('#admin-panel');
 let selected=null,generation=0,busy=false,searchTimer,roles=[];
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const note=text=>$('#admin-status').textContent=text;
 function sync(){const allowed=!!account.user?.owner;$('#admin-open').hidden=!allowed;if(!allowed){++generation;dialog.close();$('#admin-confirm').close();selected=null;$('#admin-users').replaceChildren();$('#admin-detail').replaceChildren();$('#admin-log').replaceChildren();}}
 async function search(){const token=++generation;try{const data=await account.api('/admin/users?q='+encodeURIComponent($('#admin-search').value));if(token!==generation||!account.user?.owner)return;$('#admin-users').replaceChildren(...data.users.map(user=>{const b=el('button',user.username);b.type='button';b.disabled=user.owner;b.addEventListener('click',()=>{selected=user;roles=user.roles.map(r=>({...r}));detail();});return b;}));}catch(e){note(e.message);}}
 async function audit(){try{const data=await account.api('/admin/log');if(!account.user?.owner)return;$('#admin-log').replaceChildren(...data.entries.map(entry=>{const d=JSON.parse(entry.details),row=el('p');row.textContent=new Date(entry.created).toLocaleString()+' · '+entry.action+' · '+(d.username||entry.target)+' · '+d.reason;return row;}));}catch(e){note(e.message);}}
 function field(label,node){const wrap=el('label',label);wrap.append(node);return wrap;}
 function detail(){
  const panel=$('#admin-detail');panel.replaceChildren();if(!selected)return;
  panel.append(el('h3',selected.username));const states=[];if(selected.banned)states.push('Banned');if(selected.suspendedUntil>Date.now())states.push('Suspended until '+new Date(selected.suspendedUntil).toLocaleString());if(selected.mutedUntil>Date.now())states.push('Muted until '+new Date(selected.mutedUntil).toLocaleString());panel.append(el('p',states.join(' · ')||'Account is active.'));
  const reason=el('input');reason.id='admin-reason';reason.maxLength=280;reason.placeholder='Why are you making this change?';const duration=el('select');duration.id='admin-duration';for(const [hours,label] of [[1,'1 hour'],[24,'1 day'],[168,'7 days'],[720,'30 days'],[8760,'1 year']]){const o=el('option',label);o.value=hours;duration.append(o);}panel.append(field('Reason',reason),field('Mute / suspension duration',duration));
  const actions=el('div',undefined,'admin-actions'),choice=el('select');choice.id='admin-action';
  for(const [action,label] of [['mute','Mute chat'],['unmute','Remove mute'],['suspend','Suspend account'],['unsuspend','Lift suspension'],['ban','Ban account'],['unban','Unban account']]){const option=el('option',label);option.value=action;choice.append(option);}
  const apply=el('button','Review action');apply.type='button';apply.className='admin-primary';apply.addEventListener('click',()=>void applyUser(choice.value));actions.append(field('Action',choice),apply);panel.append(actions);
  const roleEditor=el('details',undefined,'admin-role-editor');roleEditor.append(el('summary','Profile roles'),el('p','Colored labels only. No moderation permissions.'));panel.append(roleEditor);
  const roleList=el('div');roleList.id='admin-role-list';roleEditor.append(roleList);paintRoles();
  const name=el('input');name.id='admin-role-name';name.maxLength=24;name.placeholder='e.g. Community helper';const color=el('input');color.id='admin-role-color';color.type='color';color.value='#8b7bff';roleEditor.append(field('Role name',name),field('Role color',color));const add=el('button','Add role');add.type='button';add.addEventListener('click',()=>{if(!name.value.trim()||roles.length>=5){note('Enter a role name. Maximum five roles.');return;}roles.push({name:name.value.trim(),color:color.value});name.value='';paintRoles();});const save=el('button','Save roles');save.type='button';save.addEventListener('click',()=>void applyUser('roles'));roleEditor.append(add,save);
 }
 function paintRoles(){const list=$('#admin-role-list');list.replaceChildren(...roles.map((role,index)=>{const b=el('button',role.name+' ×','profile-role');b.type='button';b.style.setProperty('--role-color',role.color);b.setAttribute('aria-label','Remove '+role.name);b.addEventListener('click',()=>{roles.splice(index,1);paintRoles();});return b;}));}
 async function confirm(text){const d=$('#admin-confirm');$('#admin-confirm-text').textContent=text;d.returnValue='';d.showModal();return new Promise(resolve=>d.addEventListener('close',()=>resolve(d.returnValue==='apply'),{once:true}));}
 async function applyUser(action){
  if(!selected||busy)return;const reason=$('#admin-reason').value.trim(),hours=Number($('#admin-duration').value),user=selected;if(!reason){note('Add a reason first.');$('#admin-reason').focus();return;}
  const data={action,reason,hours,roles:roles.map(r=>({...r}))};busy=true;
  try{if(!await confirm(action+' for '+user.username+(action==='mute'||action==='suspend'?' for '+hours+' hours':'')+'? Reason: '+reason))return;if(!account.user?.owner)return;const result=await account.api('/admin/users/'+encodeURIComponent(user.id),{method:'POST',data});selected=result.user;roles=selected.roles;detail();note('Saved: '+action+' for '+user.username+'.');await audit();}catch(e){note(e.message);}finally{busy=false;}
 }
 const games=window.WACKY_GAMES||[];for(const game of games){const o=el('option');o.value=game.title||game.name||game.id;o.label=game.id;$('#admin-games').append(o);}
 async function boosts(){try{const data=await account.api('/game-boosts');if(!account.user?.owner)return;$('#admin-boosts').replaceChildren(...data.games.map(g=>el('p',(games.find(x=>x.id===g.id)?.title||g.id)+': +'+g.bonus)));}catch(e){note(e.message);}}
 $('#admin-boost-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const value=$('#admin-game').value,game=games.find(g=>g.id===value||(g.title||g.name)===value);if(!game){note('Choose a game from the list.');return;}const data={gameId:game.id,bonus:Number($('#admin-bonus').value),reason:$('#admin-boost-reason').value.trim()};busy=true;try{if(!await confirm('Set '+(game.title||game.id)+' bonus to '+data.bonus+'?'))return;if(!account.user?.owner)return;await account.api('/admin/boost',{method:'POST',data});note('Popularity bonus saved.');await boosts();await audit();void window.WackyPopularity?.invalidate();}catch(error){note(error.message);}finally{busy=false;}});
 function tab(name){document.querySelectorAll('[data-admin-section]').forEach(s=>s.hidden=s.dataset.adminSection!==name);document.querySelectorAll('[data-admin-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.adminTab===name)));}
 document.querySelectorAll('[data-admin-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.adminTab)));
 async function open(q=''){if(!account.user?.owner)return;$('#admin-search').value=q;tab('people');note('');if(!dialog.open)dialog.showModal();await search();void audit();void boosts();}
 $('#admin-open').addEventListener('click',()=>void open());$('#admin-search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(search,250);});window.WackyAdmin={open};window.addEventListener('wacky-account-change',sync);sync();
})();
