const {chromium}=require('C:/Users/mrell/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1920,height:1080}});
 const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173');
 await page.locator('.game-card').first().waitFor();
 const count=await page.locator('.game-card').count();assert.equal(count,405);
 assert.equal(await page.locator('.game-card img').count(),0);
 const size=await page.locator('.game-card').first().boundingBox();
 assert(size.width>=275 && size.width<=281);assert(size.height>=170 && size.height<=176);
 await page.screenshot({path:'catalog-preview.png'});
 await page.locator('#search').fill('zzznomatchzz');
 assert(await page.locator('#empty').isVisible());
 await page.locator('#search').fill('Trombone Champ');
 assert.equal(await page.locator('.game-card').count(),1);
 await page.locator('.game-card').click();
 const launch=await page.locator('#game-stage iframe').getAttribute('src');
 assert(launch.startsWith('library/noah/games/'));
 await page.locator('#fullscreen').click();
 await page.waitForFunction(()=>!!document.fullscreenElement);
 await page.locator('#fullscreen').click();
 await page.waitForFunction(()=>!document.fullscreenElement);
 await page.locator('#reload').click();
 assert.equal(await page.locator('#game-stage iframe').getAttribute('src'),launch);
 await page.locator('#close').click();
 assert.equal(await page.locator('#game-stage iframe').count(),0);
 assert.equal(await page.locator('#search').inputValue(),'Trombone Champ');
 await page.locator('#search').fill('');
 await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));
 assert(await page.evaluate(()=>scrollY>1000));
 console.log(JSON.stringify({count,cardSize:size,search:true,scroll:true,player:true,reload:true,fullscreen:true,close:true,errors},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
