ALTER TABLE users ADD COLUMN banner_color TEXT NOT NULL DEFAULT '#24242c';
ALTER TABLE users ADD COLUMN roles TEXT NOT NULL DEFAULT '[]';
ALTER TABLE users ADD COLUMN muted_until INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN suspended_until INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN banned INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS admin_log(id INTEGER PRIMARY KEY AUTOINCREMENT,actor TEXT NOT NULL,target TEXT NOT NULL,action TEXT NOT NULL,details TEXT NOT NULL,created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS game_boosts(game_id TEXT PRIMARY KEY,bonus INTEGER NOT NULL CHECK(bonus>=0),updated INTEGER NOT NULL);
