import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {chat} from './chat.mjs';
const db=new DatabaseSync(':memory:');
for(const file of ['schema.sql','chat-schema.sql','group-schema.sql'])db.exec(readFileSync(new URL(file,import.meta.url),'utf8'));
const DB={prepare(sql){const make=(args=[])=>({bind(...a){return make(a)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return {meta:db.prepare(sql).run(...args)}}});return make()},async batch(items){db.exec('BEGIN');try{const result=[];for(const s of items)result.push(await s.run());db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}};
for(const id of ['a','b','c','outsider'])db.prepare('INSERT INTO users(id,username,username_key,salt,password_hash,created) VALUES(?,?,?,?,?,?)').run(id,id,id,'s','h',1);
let now=Date.now(),sequence=0;
async function req(id,path,method='GET',data){try{return await chat({request:new Request('https://test'+path,{method}),url:new URL('https://test'+path),env:{DB},me:db.prepare('SELECT * FROM users WHERE id=?').get(id),now,body:async()=>data,fail:(status,message)=>{throw Object.assign(new Error(message),{status})},json:(data,status=200)=>({status,data}),validJPEG:()=>true})}catch(e){if(!e.status)throw e;return {status:e.status}}}
const post=(id,to,text='hello',extra={})=>req(id,'/chat/messages','POST',{to,text,clientId:'group-test-message-'+(++sequence),...extra});
assert.equal((await req('a','/chat/groups','POST',{name:'bad',members:['b','b']})).status,400);
assert.equal((await req('a','/chat/groups','POST',{name:'bad',members:['b','missing']})).status,400);
const created=await req('a','/chat/groups','POST',{name:'Friends',members:['b','c']});assert.equal(created.status,201);
const group=created.data.group.id,to='group:'+group;
assert.equal((await req('b','/chat/groups')).data.groups.length,1);assert.equal((await req('outsider','/chat/groups')).data.groups.length,0);
assert.equal((await post('a',to,'private')).status,201);
let message=(await req('b','/chat/messages?to='+to)).data.messages[0];assert.equal(message.text,'private');assert.equal(message.expires,now+86400000);
assert.equal((await req('outsider','/chat/messages?to='+to)).status,404);assert.equal((await post('outsider',to)).status,404);
assert.equal((await req('outsider','/chat/messages')).data.messages.length,0);assert.equal((await req('a','/chat/messages?to=b')).data.messages.length,0);
assert.equal((await req('b','/chat/unread')).data.count,1);assert.equal((await req('a','/chat/unread')).data.count,0);
assert.equal((await req('b','/chat/read','POST',{to,through:message.id})).status,200);assert.equal((await req('b','/chat/unread')).data.count,0);
assert.equal((await req('outsider','/chat/read','POST',{to,through:message.id})).status,404);
db.prepare('UPDATE chat_messages SET photo=? WHERE id=?').run('data:image/jpeg;base64,test',message.id);
assert.equal((await req('b','/chat/photos/'+message.id)).status,200);assert.equal((await req('outsider','/chat/photos/'+message.id)).status,404);
now+=3000;assert.equal((await post('b',to,'reply',{replyTo:message.id})).status,201);
assert.equal((await post('c',null,'leak',{replyTo:message.id})).status,400);
now+=11000;const other=(await req('b','/chat/groups','POST',{name:'Other',members:['a','c']})).data.group;
assert.equal((await post('c','group:'+other.id,'leak',{replyTo:message.id})).status,400);
db.prepare('UPDATE users SET muted_until=? WHERE id=?').run(now+10000,'c');assert.equal((await post('c',to)).status,403);assert.equal((await req('c','/chat/groups','POST',{name:'Muted',members:['a','b']})).status,403);
assert.equal((await req('b','/chat/groups/'+group+'/leave','POST',{})).status,200);
assert.equal((await req('b','/chat/messages?to='+to)).status,404);assert.equal((await req('b','/chat/photos/'+message.id)).status,404);assert.equal((await post('b',to)).status,404);
now+=86400001;assert.equal((await req('a','/chat/messages?to='+to)).data.messages.length,0);assert.equal((await req('a','/chat/photos/'+message.id)).status,404);assert.equal((await req('c','/chat/unread')).data.count,0);
await req('a','/chat/groups/'+group+'/leave','POST',{});await req('c','/chat/groups/'+group+'/leave','POST',{});assert.equal(db.prepare('SELECT COUNT(*) AS n FROM chat_groups WHERE id=?').get(group).n,0);
console.log('PASS: group creation, membership, outsider/left-member message and photo denial, public/DM isolation, cross-room replies, unread receipts, mute enforcement, 24h expiry, empty-group cleanup.');
